name: Test HF Model Inspector

on:
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🤗 HF Model Inspector
        uses: ParagEkbote/hf-transformers-model-inspector@v1.0.2
        with:
          repo_id: google-bert/bert-base-uncased
          json_output: false

      - name: Show Inspection Report in Logs
        run: cat model_inspection_report.md || echo "⚠️ Report not generated"

      - name: Upload Inspection Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-inspection-report
          path: model_inspection_report.md
